### ISSUE TITLE
Representing Array of Objects

### ISSUE THREAD

**Issue by KaranHotwani** [apidoc/apidoc#1171] opened 2022-02-22 12:53 UTC
# Feature request

I want to represent the success response for an api where I get state as an array of objects. Currently the only available type is String[], which is array of strings.

E.g responseData: {
        data:[{name:"Karan",age:10}]
}

If I want to represent this above response in @apiSuccess or @apiError in my document, there is no way. I am not able to represent that data array can have multiple objects of type{name,age}
Thanks.

**Comment by NicolasCARPi** [comment] 2022-02-22 16:09
Closing as duplicate of #993

**Closed by NicolasCARPi** 2022-02-22 16:09 UTC
