### ISSUE TITLE
Parameter getting mixed

### ISSUE THREAD

**Issue by vsachini** [apidoc/apidoc#955] opened 2021-03-31 04:33 UTC
I'm trying to generate the docs with nested params but the param with type "Object" is not on the top of the "Child".

The code:
```
 * @apiParam {String} magicLinkToken
 * @apiParam {String} firstName
 * @apiParam {String} [middleName]
 * @apiParam {String} lastName
 * @apiParam {String} [maidenName]
 * @apiParam {String} email
 * @apiParam {String} [aboutMe]
 * @apiParam {Date}   [birthDate]
 * @apiParam {String} [birthCountry]
 * @apiParam {String = MALE,FEMALE,NON_BINARY} gender
 *
 * @apiParam {Object} profilePictureFile Image Object
 * @apiParam {String} profilePictureFile[data] Image on Base 64
 * @apiParam {String} profilePictureFile[type] Type of file
 *
 * @apiParam {Number} [guardianId]
 ```
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/51142321/113090629-d0844100-921c-11eb-95d4-b4db54822909.png">

I have also tried using [], like the documentation says, but it doesn't work 
```
 * @apiParam {Object} profilePictureFile Image Object
 * @apiParam {String} profilePictureFile[data] Image on Base 64
 * @apiParam {String} profilePictureFile[type] Type of file
```
 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/51142321/113090677-e560d480-921c-11eb-8fb7-deebd82d751d.png">

# Edit

It just works if I put the Object first:
```
 * @apiParam {Object} [profilePictureFile] Image Object
 * @apiParam {String} profilePictureFile.data Image on Base 64
 * @apiParam {String} profilePictureFile.type Type of file
 *
 * @apiParam {String} magicLinkToken
 * @apiParam {String} firstName
 * @apiParam {String} [middleName]
 * @apiParam {String} lastName
 * @apiParam {String} [maidenName]
 * @apiParam {String} email
 * @apiParam {String} [aboutMe]
 * @apiParam {Date}   [birthDate]
 * @apiParam {String} [birthCountry]
 * @apiParam {String = MALE,FEMALE,NON_BINARY} gender
 * @apiParam {Number} [guardianId]
 ```
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/51142321/113090949-7f288180-921d-11eb-9da8-3e437dc75473.png">

# Information

- Version of apidoc: 0.27.1

**Comment by NicolasCARPi** [comment] 2021-03-31 16:19
Thanks for the report.

**Comment by singla96** [comment] 2021-04-12 06:42
Facing similar issue.

@apiParam {Object[]} obj some desc
@apiParam {Object} obj.abc data object
@apiParam {Number} obj.abc.identifier id of object

its displaying
abc
obj
identifier

Wrong ordering but correct indentation

**Comment by zhangky01** [comment] 2021-04-26 07:32
Facing similar issue too

@apiSuccess {Number} code
@apiSuccess {Object} data
@apiSuccess {Number} data.id
@apiSuccess {String} data.name

its displaying
data
code
  id
  name

**Comment by xinhuoshixincha** [comment] 2021-05-06 14:00
Facing similar issue too

@apiSuccess {String} message
@apiSuccess {Object} data
@apiSuccess {Object} data.header
@apiSuccess {Object} data.body
@apiSuccess {Object[]} data.body.articles
@apiSuccess {Number} data.body.articles.id
@apiSuccess {String} data.body.article.title

its displaying
data
message
    body
    header
        articles
            id
            title

but when i write like this it's right:
@apiSuccess {String} message
@apiSuccess {Object[]} data
@apiSuccess {Object[]} data.header
@apiSuccess {Object[]} data.body
@apiSuccess {Object[]} data.body.articles
@apiSuccess {Number} data.body.articles.id
@apiSuccess {String} data.body.article.title

**Comment by xinhuoshixincha** [comment] 2021-05-11 08:45
> Facing similar issue too
> 
> @apiSuccess {String} message
> @apiSuccess {Object} data
> @apiSuccess {Object} data.header
> @apiSuccess {Object} data.body
> @apiSuccess {Object[]} data.body.articles
> @apiSuccess {Number} data.body.articles.id
> @apiSuccess {String} data.body.article.title
> 
> its displaying
> data
> message
> body
> header
> articles
> id
> title
> 
> but when i write like this it's right:
> @apiSuccess {String} message
> @apiSuccess {Object[]} data
> @apiSuccess {Object[]} data.header
> @apiSuccess {Object[]} data.body
> @apiSuccess {Object[]} data.body.articles
> @apiSuccess {Number} data.body.articles.id
> @apiSuccess {String} data.body.article.title

The problem was solved by writing like this:
@apiDefine Success
@apiSuccess {String} message
@apiSuccess {Object} data

@apiUse Success
@apiSuccess {Object} data.header
@apiSuccess {Object} data.body
@apiSuccess {Object[]} data.body.articles
@apiSuccess {Number} data.body.articles.id
@apiSuccess {String} data.body.article.title

the display is accurate.

**Comment by Shahar-S** [comment] 2021-05-12 10:42
> I had to downgrade to version 0.25.0 to avoid this very same problem.

Thanks, 0.25.0 didn't fix my issue with @apiParam

**Comment by DoralLee** [comment] 2021-06-18 08:44
0.28.1 Facing similar issue too, Please solve it as soon as possible. Thank you @NicolasCARPi @singla96 @zhangky01

**Comment by NicolasCARPi** [comment] 2021-06-26 18:55
See my comment https://github.com/apidoc/apidoc/issues/968#issuecomment-869046654

Closing as duplicate of #968

**Closed by NicolasCARPi** 2021-06-26 18:55 UTC
Labels: bug
