### ISSUE TITLE
Directive "template"->"withCompare" in config provoke error

### ISSUE THREAD

**Issue by bondalex96** [apidoc/apidoc#878] opened 2020-05-06 09:47 UTC
I use the last version of apidoc. Recently I've discovered generated documentation show nothing except titles. In console I've seen the next error
![image](https://user-images.githubusercontent.com/20372412/81162251-89061e00-8f95-11ea-8bff-ee99d99af8e0.png)
 
# Steps to reproduce
My config had next view.
{
  "name": "Project Name",
  "version": "0.1.0",
  "description": "",
  "title": "Project Title",
  "template": {
    "withCompare": false
  }
}
If I set template->withCompare = true, error disappears.

# Information

- Version of apidoc: @0.22.0
- Operating system: GNU+Linux:
- Browser: Chrome

**Comment by NicolasCARPi** [comment] 2020-05-06 12:44
Do you have defined different versions of your api?

**Comment by NicolasCARPi** [comment] 2020-05-07 16:44
I'll just close this as duplicate of #879 as the newer issue contains more info.

**Closed by NicolasCARPi** 2020-05-07 16:44 UTC

**Comment by bondalex96** [comment] 2020-05-07 17:29
> Do you have defined different versions of your api?

No, i don't use different versions.
