### ISSUE TITLE
"required" label doesn't work

### ISSUE THREAD

**Issue by pacoogle** [apidoc/apidoc#1174] opened 2022-02-24 14:04 UTC
# Describe the bug

I needed to make input parameter as "required" but FE doesn't show it

# Steps to reproduce

~~~javascript
/**
 * @api {put} /v2/users/:uid Edit Users information
 * @apiName EditUser
 * @apiGroup User
 *
 * @apiParam {String} uid Crypted <code>id</code> of the user.
 * 
 * @apiHeader {String} Authorization The token can be generated with /v2/tokens call.
 * @apiHeaderExample {Header} Header-Example
 *     "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvZW1iZWRkZWQuYXBpLmdhbWluZG8uY29tIiwiaWF0IjoxNjQ1NjI1MDQyLCJleHAiOjE2NDU2MjU2NDJ9.GRaYHqNkMFy3fXQBg1zgu25R1KDQOw-rGHA4JLB7YBE"
 * 
 * @apiBody {String} [username] User username
 * @apiBody {String} [email] User email
 * @apiBody {String} [details] This field can be unstructured/structured string as JSON
 * 
 * @apiSuccess {String} uid Crypted User ID
 * @apiSuccess {String|null} username User's username
 * @apiSuccess {String|null} email User's email
 * @apiSuccess {String|null} details User's details
 * @apiSuccess {String|null} winning Details about winning call
 * 
 * @apiSuccessExample {json} Success-Response:
                   [
                      {
                          "uid": "eyJpdiI6Ik51Ukt5UjlISkxSODRxMTV0dlJoK0E9PSIsInZhbHVlIjoiUC9MMnJhV3pUZDZQeXNLVEthQTAvdz09IiwibWFjIjoiOTM5NWU2Y2Y4OWE0MDI2ODRjYmJkZTc4NGM0YWQ4NDhlN2UxNGY1MTcyMDdhZDZjNzNkNjUyYWFjZmM2NDliYiJ9",
                          "username": "pippo5",
                          "email": "test5@gmail.com",
                          "details": "{'chiave':'valore'}",
                          "winning": null
                      }
                  ]
 * @apiError {Bool} success Success details
 * @apiError {String} message Error details   
 * @apiErrorExample {json} Success-Response:
                   [
                      {
                          "success": false,
                          "message": "User not exists"
                      }
                  ]           
  *
  * 
 */
function EditUser() {}

# Information

{
  "name": "Api documentation",
  "version": "2.0.0",
  "description": "Documentation for the REST api access provided",
  "title": "Gamindo - API doc",
  "url": "",
  "sampleUrl": "",
  "output": "/tmp/apidoc-output",
  "input": ["example"],
  "order": ["User"],
  "header": {
    "title": "Authentication",
    "filename": "header.md"
  },
  "template": {
    "showRequiredLabels": true,
    "withCompare": true,
    "withGenerator": true,
    "aloneDisplay": false
  }
}

~~~

**Comment by NicolasCARPi** [comment] 2022-02-24 14:26
>  but FE doesn't show it

FE ??


Anyway, seems to work fine here.
![2022-02-24-152552_574x225_scrot](https://user-images.githubusercontent.com/3043706/155542664-1f5c8ea7-b631-4872-aa00-439e234bc768.png)

**Comment by steven-t-h** [comment] 2022-07-15 09:20
@NicolasCARPi I'm having the same issue. Regardless of the `showRequiredLabels` value in my apidoc.json I don't see any required flags. This is the same whether I use my package.json or apidoc.json.

**Comment by steven-t-h** [comment] 2022-07-16 08:27
@NicolasCARPi yes, I actually have the same exact issue as @pacoogle which I think is more of a feature request. The required label only shows if the request also contains optional params.

**Comment by NicolasCARPi** [comment] 2022-07-16 13:24
> The required label only shows if the request also contains optional params.

Well, not in my hands. Would be great if someone could provide a minimal reproducible case/code.

If the input contains only this:

~~~javascript
/**
 * @api {put} /v2/users/:uid Edit Users information
 * @apiName EditUser
 * @apiGroup User
 *
 * @apiBody {String} User username
 */
function EditUser() {}
~~~

You say it should not show the required label because there are no optional entries, right? But it does.


![2022-07-16-152317_775x309_scrot](https://user-images.githubusercontent.com/3043706/179356763-a8d4e976-3735-4391-9fc7-74abf0da89bc.png)

**Comment by tuyentq4995** [comment] 2022-07-30 04:10
@NicolasCARPi 
Required label only show when use @apiBody
@apiParam not works, Can add required label for  @apiParam?

**Comment by steven-t-h** [comment] 2022-07-31 19:37
@NicolasCARPi nothing has changed on my end, but now everything is working fine. Wish I had any idea why.

**Comment by NicolasCARPi** [comment] 2022-08-02 11:05
Can you try the `dev` branch? I pushed a fix on it for this issue.

**Closed** 2022-09-06 11:17 UTC
Labels: not reproducible
