### ISSUE TITLE
Feature request: documenting object types and linking to it from apiParam

### ISSUE THREAD

**Issue by sabat24** [apidoc/apidoc#754] opened 2018-10-30 15:03 UTC
In many cases in my responses I use predefined object types like userStructure or productStructure etc. Right now there is no convinient way for final user who is reading the doc, to get information about data structures (DTOs).

**Comment by solsticesurfer** [comment] 2019-02-04 18:59
You can do this but it's a hack.

In your object, you have to have **two** apidoc declarations. The first is the @apiDefine block that specifies the @apiGroup and a list of @apiSuccess entries for each attribute.

Then you create a duplicate of that block, remove the @apiDefine and add an @api declaration in its place. 

Using this approach, you can create entries for your data objects. They will have an api endpoint listed which is not ideal but, as this project does not seem to be maintained any longer, it will at least provide you with something useful.

Using your `productStructure` object, here is an example:

```
/**
* @apiDefine productStructure
* @apiGroup ProductService
* @apiSuccess {String} sku
* @apiSuccess {String} name
* @apiSuccess {String} description
*/
/*
* @api {Object}  / productStructure
* @apiName productStructure
* @apiGroup ProductService
* @apiSuccess {String} sku
* @apiSuccess {String} name
* @apiSuccess {String} description
*/
```

**Closed** 2019-10-19 22:47 UTC
