### ISSUE TITLE
Name must contain only alphanumeric characters.

### ISSUE THREAD

**Issue by seanmars** [apidoc/apidoc#638] opened 2017-05-07 13:06 UTC
I want use apiDefine with dot(like Math.Abs), but got this error.
```
Name must contain only alphanumeric characters.
```
Sometimes  we have same method or object name under different namespace.
Can supported this feature? Or Just that apiGroup work on apiDefine ?

**Comment by NicolasCARPi** [comment] 2019-10-19 23:05
Duplicate of #774

**Closed by NicolasCARPi** 2019-10-19 23:05 UTC
