### ISSUE TITLE
Impossible to specify request parameter with dollar sign

### ISSUE THREAD

**Issue by annam002** [apidoc/apidoc#825] opened 2019-12-13 09:14 UTC
# Describe the bug

We are using @apiParam to specify our request parameters. One of the parameter has a dollar sign in it. Unfortunately, apidoc cannot parse the dollar, nor any variation like $dollar; u+0024;, $#36;.  I always get the error 'Empty parser result.'

# Steps to reproduce
Have a parameter like this in your documentation:
@apiParam {String} [$fields]

# Information

- Version of apidoc: 0.19.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows 10 & Linux
- Browser (e.g. firefox, chrome): n.a.

**Comment by NicolasCARPi** [comment] 2019-12-13 11:14
Hello,

This is a duplicate of #506. I'm not sure how easy/difficult it would be allow the dollar sign (and maybe other characters like '@').

**Comment by NicolasCARPi** [comment] 2021-09-13 00:56
This is no longer an issue. On the `dev` branch at least.

**Closed by NicolasCARPi** 2021-09-13 00:56 UTC
Labels: feature request
