### ISSUE TITLE
Reuse success return examples

### ISSUE THREAD

**Issue by simplenotezy** [apidoc/apidoc#362] opened 2015-11-16 11:30 UTC
I have an app where a lot of my models are returned the same way. For instance; a `User` can be attached to a `Post`. When I request a `Post`, a `User` (the author) will also be returned together with the post.

Everytime I update the `User` model (i.e. add `gender` or `username` to the output) I have to change the whole documentation where a User is attached to another Model.

It could be great with a way to define a default response for a User, so that I only have to change the api documentation one place.

Something like this:

```
 * @apiSuccessExample Example
 *
 * HTTP/1.1 200 OK
 *  {
 *    "id": "1",
 *    "title": "My post",
 *    "category": {
 *      @defaultCategoryModel
 *    },
 *    "images": [
 *      {
 *        "file": "506d3e9efd72db7740f4baa653639de6.jpg"
 *      }
 *    ],
 *    "user": {
 *      @defaultUserModel
 *    }
 *  }
```

**Comment by koustuvsinha** [comment] 2016-02-05 14:50
:+1: would be useful for me too

**Comment by Telokis** [comment] 2020-05-05 09:41
This is a duplicate of https://github.com/apidoc/apidoc/issues/346

**Comment by NicolasCARPi** [comment] 2020-05-05 09:46
> This is a duplicate of #346

Closing then.

**Closed by NicolasCARPi** 2020-05-05 09:46 UTC
Labels: think about
