### ISSUE TITLE
apiSuccess parameters with object grouping

### ISSUE THREAD

**Issue by mnicolas80** [apidoc/apidoc#361] opened 2015-11-15 22:40 UTC
Hi, I am trying to describe the following response, but with no success:

`{
     "data1": {
          "var1": 0,
          "var2": "my message",
     },
     "data2": {
          "var3": "another message"
     }
}`

Here is a part of my apidoc, code:

@apiSuccess {Object} data1 descr1.
@apiSuccess (Number) data1.var1 descr2.
@apiSuccess (String) data1.var2 descr3.
@apiSuccess {Object} data2 descr5.
@apiSuccess (String) data2.var3 descr6.

The generated output does not put the variables under their parent objects, but changes the entire grouping into independent lines. Any idea?

Thank you

**Comment by NicolasCARPi** [comment] 2019-10-19 22:54
Duplicate of #548

**Closed by NicolasCARPi** 2019-10-19 22:54 UTC
